name: Deploy Flask app to AlwaysData

on:
  push:
    branches:
      - 0.1.1   # déclenche automatiquement quand il y a un push sur cette branche

  workflow_dispatch:   # permet de lancer manuellement et de choisir la branche
    inputs:
      branch:
        description: 'Nom de la branche à déployer'
        required: true
        default: '0.1.1'

env:
  APP_PATH: "/home/inventory-service/inventory_service"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AD_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.AD_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_ed25519 -o BatchMode=yes ${{ secrets.AD_USER }}@${{ secrets.AD_HOST }} "echo 'SSH connection OK'" || exit 1

      - name: Determine branch to deploy
        run: |
          # Détecte si on est en workflow_dispatch ou push
          if [ -n "${{ github.event.inputs.branch }}" ]; then
            BRANCH_TO_DEPLOY="${{ github.event.inputs.branch }}"
          else
            BRANCH_TO_DEPLOY="${GITHUB_REF##refs/heads/}"
          fi
          echo "Branch to deploy: $BRANCH_TO_DEPLOY"
          echo "BRANCH_TO_DEPLOY=$BRANCH_TO_DEPLOY" >> $GITHUB_ENV
        
        
      - name: Update code on AlwaysData
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.AD_USER }}@${{ secrets.AD_HOST }} "
            set -e
            cd \"${APP_PATH}\" || { echo 'Dossier introuvable: ${APP_PATH}'; exit 1; }
            git fetch origin
            git checkout $BRANCH_TO_DEPLOY
            git pull origin $BRANCH_TO_DEPLOY
            touch backend/passenger_wsgi.py
          "

      - name: Install Python dependencies in venv
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.AD_USER }}@${{ secrets.AD_HOST }} "
            set -e
            cd \"${APP_PATH}/backend\" || exit 1

            # Crée le venv si il n'existe pas
            if [ ! -d venv ]; then
              python3.12 -m venv venv
              echo '✅ Virtualenv créé'
            fi

            # Active le venv et installe les dépendances
            source venv/bin/activate
            ./venv/bin/pip install --upgrade pip
            ./venv/bin/pip install -r requirements.txt
          "

